Update free_snap_tap.py
Updated the Line because in python v3.11.6 I got the following error. 
 line 331
    print(f"time: {data.time}, vk_code: {vk_code} - {"press  " if is_keydown else "release"} - {"simulated" if is_simulated else "real"}")
                                                      ^^^^^
SyntaxError: f-string: expecting '}'